### ISSUE TITLE
[FEATURE REQUEST] Make DEL button work in Requests list

### ISSUE THREAD

**Issue by pingzing** [fabiobento512/FRequest#1]
Hi! This is an awesome program. I greatly prefer its UI paradigm and snappiness to Postman. I've noticed a few small usability issues. I'll lay them out in Github Issues, but if you have another preferred way to receive feedback, I can use that instead!

**Application Version**

v1.1

**Platform**

Windows 10, Fall Creators Update (Version 1709, Build 16299)

**Issue**

The DEL button doesn't remove saved Requests from the Request list.

**Expected**

DEL button has the same functionality as the right-click -> Delete flow. In addition, the right-click context menu should show the hotkey assigned to the function.

**Comment by fabiobento512** [comment]
> Hi! This is an awesome program. I greatly prefer its UI paradigm and snappiness to Postman.

Thanks! :)

> I've noticed a few small usability issues. I'll lay them out in Github Issues, but if you have another preferred way to receive feedback, I can use that instead!

I'm glad to receive feedback. It is fine to post the issues here at github, in fact I don't have any other place where they can be posted at the moment.

I will add this functionality, once I'm done I will post here.

**Comment by fabiobento512** [comment]
Implemented in 1.1a.

**Comment by fabiobento512** [comment]
@pingzing 
Just to notice you that v1.1a is now available with your suggestions. Thanks!
