### ISSUE TITLE
Please provide AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [fabiobento512/FRequest#10]
Please provide the AppImage for download on GitHub Releases, thank you.

**Comment by fabiobento512** [comment]
Hi!

It is already there. See the FRequest11c_linux.zip file. Inside of it you have the app image.

Regards.

**Comment by probonopd** [comment]
Please DO NOT put an AppImage into another archive like a `.zip` or `.tar.gz`. Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake for the reasons. 

I would like to add it to https://appimage.github.io/ but that only works if it is not zipped.

Thank you.

**Comment by probonopd** [comment]
```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-10363/AppRun)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

**Comment by probonopd** [comment]
OK, if you like to have it added to https://appimage.github.io/ please ping me once Ubuntu 14.04 is no longer supported. Thanks.

**Comment by fabiobento512** [comment]
Thanks! Sure I will do.

**Comment by danipardo** [comment]
I don't know if it will help, but I'm running Linux Mint LMDE 3 “Cindy”, and when running the AppImage, I get this:

$ ./FRequest11c_linux.AppImage 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.

**Comment by fabiobento512** [comment]
@danipardo 
I have seen that error is some distributions that I have tried. Unfortunately I don't know how to fix that.

@probonopd 
Could the problem be related with the build being done in Ubuntu 18.04.1 x64 instead of an older version?

**Comment by probonopd** [comment]
> Could the problem be related with the build being done in Ubuntu 18.04.1 x64 instead of an older version?

Definitely.

**Comment by fabiobento512** [comment]
> OK, if you like to have it added to https://appimage.github.io/ please ping me once Ubuntu 14.04 is no longer supported. Thanks.

@probonopd Can you check if the program can now be added?

**Comment by fabiobento512** [comment]
Closing as this issue is too old. This could be checked in the future.
