### ISSUE TITLE
Qt5 required 

### ISSUE THREAD

**Issue by danipardo** [fabiobento512/FRequest#12]
It won't compile with qt4, because QUrlQuery is only available since Qt5.

**Comment by fabiobento512** [comment]
Yes that's true and not only that, it requires Qt 5.10 I believe, some http functions are only available in the later versions.

But there is really a need for a Qt4 build?

**Comment by danipardo** [comment]
Sure, there's no need for Qt4. I just spotted 

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

on the qmake .pro file. Maybe it should read something like this?

greaterThan(QT_MAJOR_VERSION, 5): QT += widgets
greaterThan(QT_MINOR_VERSION, 10): QT += widgets

**Comment by fabiobento512** [comment]
Oh that was generated automatically by qtcreator.

greaterThan (>) wouldn't work the way you posted because then it would require Qt 6 and a minor version of at least 11. (greaterThan in qmake means > not >=).

But yup maybe we could adjust that for something more close to the requirements.

**Comment by danipardo** [comment]
Oh, I see, my fault then. Thanks!
