### ISSUE TITLE
Freezing with big response

### ISSUE THREAD

**Issue by felipedaragon** [fabiobento512/FRequest#18]
Hi! I noticed that when the tool receives a big HTTP response, such as a big XML response data, the application will freeze/crash.

**Comment by fabiobento512** [comment]
Hi, can you try to decrease the "Max request response data size to display" setting in Preferences? Try something like 200, 150 and 100 KB. This should stop the freezing, you will need to download then the response as file though (if you want to check the whole return).

**Comment by felipedaragon** [comment]
@fabiobento512 ok I will try this later, but it was freezing with a response smaller than 80kb

**Comment by fabiobento512** [comment]
If you try this we can open this ticket again later.
