### ISSUE TITLE
[FEATURE REQUEST] Allow custom download cutoff threshold

### ISSUE THREAD

**Issue by pingzing** [fabiobento512/FRequest#2]
**Application Version**

v1.1

**Platform**

Windows 10, Fall Creators Update (Version 1709, Build 16299)

**Request**

It would be nice to be able to configure to 200kB cutoff threshold for responses. I'd imagine it would live somewhere in preferences, as a freeform entry box.

**Comment by fabiobento512** [comment]
Yes that's in fact in the TODO list. I have even post a comment about that in the source code.

**Comment by fabiobento512** [comment]
Implemented in 1.1a.
