### ISSUE TITLE
Change timeout time

### ISSUE THREAD

**Issue by Themis3000** [fabiobento512/FRequest#28]
I just got this program and I'm enjoying it, however it would be quite nice to be able to turn up the timeout time. Maybe I'm wrong in thinking this is the fault of the client, or I'm missing that this feature already exists so it any of these things are true let me know.

It would be nice because when debugging code it's nice to have no timeout time while you step through lines of code one by one.

**Comment by fabiobento512** [comment]
You can already do that in Options->Preferences:
![image](https://user-images.githubusercontent.com/35874147/178134415-955f474f-68f5-42fb-a898-d85cb575ac5f.png)

If that doesn't work let me know.

**Comment by Themis3000** [comment]
Thank you for the quick response! Not sure how I missed that. I looked over that menu multiple times and it never clicked, I must be getting tired 😅
