### ISSUE TITLE
[FEATURE REQUEST] Expose "Rename Request (or Project)" functionality in the right-click context menu

### ISSUE THREAD

**Issue by pingzing** [fabiobento512/FRequest#3]
**Application Version**

v1.1

**Platform**

Windows 10, Fall Creators Update (Version 1709, Build 16299)

**Issue**

Currently, the only way to rename a Project is the press F2, or Right Click -> Project Properties. The _only_ way to rename a Request is with F2.

**Expected**

Both Projects and Requests can be renamed with F2, or with a Right-Click + Rename. The Rename button in the context menu should list the hotkey, as well.

**Comment by fabiobento512** [comment]
You can also rename them double clicking in the name with the mouse. By knowing this let me know if you still need the rename context menu entry.

**Comment by pingzing** [comment]
Speaking personally, I'd still prefer it, mostly because _not_ finding it in a right-click menu came as a surprise. I expect I'm not in the minority here. It'd improve discovery, though there is a danger of eventually cluttering up those menus too much, I suppose.

**Comment by fabiobento512** [comment]
Indeed I agree that it improves the discovery of the option. I will add the rename option to the context menu.

**Comment by fabiobento512** [comment]
Implemented in 1.1a.
