### ISSUE TITLE
Feature request: Allow to create subfolders for bundling related requests

### ISSUE THREAD

**Issue by piula** [fabiobento512/FRequest#34]
Hello,

I like your program for its simplicity. But sometimes, I wish there was a possibility to create subfolders to sort requests into.

The background is that I always create a related request when I add a new REST endpoint so that I can see whether it works as expected. As time goes by, the list gets longer and longer, of course, finally lacking clarity.

**Comment by fabiobento512** [comment]
Hello,

Thanks for your suggestion.

There is already an issue for this, here:
https://github.com/fabiobento512/FRequest/issues/17

I am closing this one. Even though it is not a replacement, I recommend that you the filter if possible to find the requests quicker, until this feature is implemented (no promises though).
