### ISSUE TITLE
[FEATURE REQUEST] Open the last-opened project by default

### ISSUE THREAD

**Issue by pingzing** [fabiobento512/FRequest#4]
**Application Version**

v1.1

**Platform**

Windows 10, Fall Creators Update (Version 1709, Build 16299)

**Request**

My workflow usually involves working on the same project several days in a row, and removing an extra hitch in getting up and running would be greatly appreciated. 

Alternately, make a setting for a "default project", but everyone knows "make it a setting" is a cop-out =)

**Comment by fabiobento512** [comment]
> Open the last-opened project by default

I can add a option for this in preferences.

> Alternately, make a setting for a "default project", but everyone knows "make it a setting" is a cop-out =)

Yes I can also add this I guess. I will think about the interface for it later.

Let me know if you prefer both options or if open the last project automatically is enough.

**Comment by pingzing** [comment]
Personally, I'd be perfectly happy with the "open last project automatically" behavior. It's a familiar concept, and easy enough to change without needing a separate entry in a settings menu.

**Comment by fabiobento512** [comment]
I guess I will add the following option to the preferences dialog (a combobox, it should be very easy to add):
**Open last project on startup: [Never, Always, Ask]**

**Comment by fabiobento512** [comment]
Added on 1.1a:
![image](https://user-images.githubusercontent.com/35874147/35591456-e95c5f00-0601-11e8-88fd-98ed07761f80.png)
