### ISSUE TITLE
An error ocurred while creating the FRequest config file. Application needs to abort.

### ISSUE THREAD

**Issue by codrin91** [fabiobento512/FRequest#5]
An error ocurred while creating the FRequest config file. Application needs to abort.
What I need to do?

**Comment by fabiobento512** [comment]
Hi, please provide more information, including:

- Operating System
- How did you installed the application
- FRequest log file if available
- Description what you were doing before that message appeared

Also make sure you extract all files from the zip to a folder where FRequest is able to write (something like documents folder in windows).

**Comment by codrin91** [comment]
• Mac os 10.13.2 
•I'm download [FRequest11_macos.zip](https://github.com/fabiobento512/FRequest/releases/download/v1.1/FRequest11_macos.zip)
• FRequest don't make an log file
• 
<img width="797" alt="schermata 2018-01-30 alle 15 34 23" src="https://user-images.githubusercontent.com/19703401/35571656-17a90c5c-05d3-11e8-9967-da400b42116c.png">

If I go to ~/FRequest.app/Contents/MacOS/FRequest  and open it, the App Starts.

**Comment by fabiobento512** [comment]
Thanks I will check this later on my machine, I will upgrade to 10.13 to try to reproduce your problem.

**Comment by fabiobento512** [comment]
I confirmed the problem on 10.13.1. 

I will fix this for the version 1.1a which hopefully will be released this weekend.

**Comment by fabiobento512** [comment]
Btw as work around you can use the following command in the same folder of FRequest.app:
sudo xattr -d -r -s com.apple.quarantine FRequest.app/

This will remove the "App Translocation" as described here:
https://apple.stackexchange.com/questions/262570/oddly-randomized-mounted-paths-in-sierra-for-certain-apps

**Comment by codrin91** [comment]
Perfect, it's works 💯

**Comment by fabiobento512** [comment]
I have just tested and there's also another workaround for this problem, you can simply move (using finder) the FRequest.app to a folder that you write permissions like the "Documents" folder, this way "App Translocation" doesn't happen when you open the application:
![frequestmacosrunworkaround](https://user-images.githubusercontent.com/35874147/35703624-a37196e2-0794-11e8-8067-57794f3fb118.png)

I will add this image to the error message when FRequest can't create the config file on macOS, so users can do the procedure above to bypass the problem. This will be in the version 1.1a.

**Comment by fabiobento512** [comment]
Ok I have added the information to workaround this problem in the error message now, for the macOS users. It be present in the version 1.1a. I will now close this issue.
